/**
 * My API - V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ne bydet
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BugetPlanView model module.
 * @module model/BugetPlanView
 * @version v1
 */
class BugetPlanView {
    /**
     * Constructs a new <code>BugetPlanView</code>.
     * @alias module:model/BugetPlanView
     */
    constructor() { 
        
        BugetPlanView.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BugetPlanView</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BugetPlanView} obj Optional instance to populate.
     * @return {module:model/BugetPlanView} The populated <code>BugetPlanView</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BugetPlanView();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('january')) {
                obj['january'] = ApiClient.convertToType(data['january'], 'Number');
            }
            if (data.hasOwnProperty('february')) {
                obj['february'] = ApiClient.convertToType(data['february'], 'Number');
            }
            if (data.hasOwnProperty('march')) {
                obj['march'] = ApiClient.convertToType(data['march'], 'Number');
            }
            if (data.hasOwnProperty('april')) {
                obj['april'] = ApiClient.convertToType(data['april'], 'Number');
            }
            if (data.hasOwnProperty('may')) {
                obj['may'] = ApiClient.convertToType(data['may'], 'Number');
            }
            if (data.hasOwnProperty('june')) {
                obj['june'] = ApiClient.convertToType(data['june'], 'Number');
            }
            if (data.hasOwnProperty('july')) {
                obj['july'] = ApiClient.convertToType(data['july'], 'Number');
            }
            if (data.hasOwnProperty('august')) {
                obj['august'] = ApiClient.convertToType(data['august'], 'Number');
            }
            if (data.hasOwnProperty('september')) {
                obj['september'] = ApiClient.convertToType(data['september'], 'Number');
            }
            if (data.hasOwnProperty('october')) {
                obj['october'] = ApiClient.convertToType(data['october'], 'Number');
            }
            if (data.hasOwnProperty('november')) {
                obj['november'] = ApiClient.convertToType(data['november'], 'Number');
            }
            if (data.hasOwnProperty('december')) {
                obj['december'] = ApiClient.convertToType(data['december'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BugetPlanView</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BugetPlanView</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} id
 */
BugetPlanView.prototype['id'] = undefined;

/**
 * @member {Number} january
 */
BugetPlanView.prototype['january'] = undefined;

/**
 * @member {Number} february
 */
BugetPlanView.prototype['february'] = undefined;

/**
 * @member {Number} march
 */
BugetPlanView.prototype['march'] = undefined;

/**
 * @member {Number} april
 */
BugetPlanView.prototype['april'] = undefined;

/**
 * @member {Number} may
 */
BugetPlanView.prototype['may'] = undefined;

/**
 * @member {Number} june
 */
BugetPlanView.prototype['june'] = undefined;

/**
 * @member {Number} july
 */
BugetPlanView.prototype['july'] = undefined;

/**
 * @member {Number} august
 */
BugetPlanView.prototype['august'] = undefined;

/**
 * @member {Number} september
 */
BugetPlanView.prototype['september'] = undefined;

/**
 * @member {Number} october
 */
BugetPlanView.prototype['october'] = undefined;

/**
 * @member {Number} november
 */
BugetPlanView.prototype['november'] = undefined;

/**
 * @member {Number} december
 */
BugetPlanView.prototype['december'] = undefined;






export default BugetPlanView;

