/**
 * My API - V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ne bydet
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ExpenseView model module.
 * @module model/ExpenseView
 * @version v1
 */
class ExpenseView {
    /**
     * Constructs a new <code>ExpenseView</code>.
     * @alias module:model/ExpenseView
     */
    constructor() { 
        
        ExpenseView.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ExpenseView</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ExpenseView} obj Optional instance to populate.
     * @return {module:model/ExpenseView} The populated <code>ExpenseView</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ExpenseView();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('confirm')) {
                obj['confirm'] = ApiClient.convertToType(data['confirm'], 'Boolean');
            }
            if (data.hasOwnProperty('valid')) {
                obj['valid'] = ApiClient.convertToType(data['valid'], 'Boolean');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('expenseTypeId')) {
                obj['expenseTypeId'] = ApiClient.convertToType(data['expenseTypeId'], 'Number');
            }
            if (data.hasOwnProperty('employeeId')) {
                obj['employeeId'] = ApiClient.convertToType(data['employeeId'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ExpenseView</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ExpenseView</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} id
 */
ExpenseView.prototype['id'] = undefined;

/**
 * @member {Boolean} confirm
 */
ExpenseView.prototype['confirm'] = undefined;

/**
 * @member {Boolean} valid
 */
ExpenseView.prototype['valid'] = undefined;

/**
 * @member {Date} date
 */
ExpenseView.prototype['date'] = undefined;

/**
 * @member {Number} amount
 */
ExpenseView.prototype['amount'] = undefined;

/**
 * @member {Number} expenseTypeId
 */
ExpenseView.prototype['expenseTypeId'] = undefined;

/**
 * @member {Number} employeeId
 */
ExpenseView.prototype['employeeId'] = undefined;






export default ExpenseView;

