/**
 * My API - V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ne bydet
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MyApiV1);
  }
}(this, function(expect, MyApiV1) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MyApiV1.BugetPlanView();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BugetPlanView', function() {
    it('should create an instance of BugetPlanView', function() {
      // uncomment below and update the code to test BugetPlanView
      //var instance = new MyApiV1.BugetPlanView();
      //expect(instance).to.be.a(MyApiV1.BugetPlanView);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new MyApiV1.BugetPlanView();
      //expect(instance).to.be();
    });

    it('should have the property january (base name: "january")', function() {
      // uncomment below and update the code to test the property january
      //var instance = new MyApiV1.BugetPlanView();
      //expect(instance).to.be();
    });

    it('should have the property february (base name: "february")', function() {
      // uncomment below and update the code to test the property february
      //var instance = new MyApiV1.BugetPlanView();
      //expect(instance).to.be();
    });

    it('should have the property march (base name: "march")', function() {
      // uncomment below and update the code to test the property march
      //var instance = new MyApiV1.BugetPlanView();
      //expect(instance).to.be();
    });

    it('should have the property april (base name: "april")', function() {
      // uncomment below and update the code to test the property april
      //var instance = new MyApiV1.BugetPlanView();
      //expect(instance).to.be();
    });

    it('should have the property may (base name: "may")', function() {
      // uncomment below and update the code to test the property may
      //var instance = new MyApiV1.BugetPlanView();
      //expect(instance).to.be();
    });

    it('should have the property june (base name: "june")', function() {
      // uncomment below and update the code to test the property june
      //var instance = new MyApiV1.BugetPlanView();
      //expect(instance).to.be();
    });

    it('should have the property july (base name: "july")', function() {
      // uncomment below and update the code to test the property july
      //var instance = new MyApiV1.BugetPlanView();
      //expect(instance).to.be();
    });

    it('should have the property august (base name: "august")', function() {
      // uncomment below and update the code to test the property august
      //var instance = new MyApiV1.BugetPlanView();
      //expect(instance).to.be();
    });

    it('should have the property september (base name: "september")', function() {
      // uncomment below and update the code to test the property september
      //var instance = new MyApiV1.BugetPlanView();
      //expect(instance).to.be();
    });

    it('should have the property october (base name: "october")', function() {
      // uncomment below and update the code to test the property october
      //var instance = new MyApiV1.BugetPlanView();
      //expect(instance).to.be();
    });

    it('should have the property november (base name: "november")', function() {
      // uncomment below and update the code to test the property november
      //var instance = new MyApiV1.BugetPlanView();
      //expect(instance).to.be();
    });

    it('should have the property december (base name: "december")', function() {
      // uncomment below and update the code to test the property december
      //var instance = new MyApiV1.BugetPlanView();
      //expect(instance).to.be();
    });

  });

}));
